---
collections:
  # Install a collection from Ansible Galaxy.
  - name: ansible.posix
    version: 1.2.0
    source: https://galaxy.ansible.com
  - name: community.general
    version: 3.5.0
    source: https://galaxy.ansible.com
