# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git
	copydir
	copyfile
	docker
	git-extras
	jsontools
	ng
        zsh-completions
)

export FPATH="~/.zsh.d:$FPATH"

source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit

# User configuration

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

export EDITOR="$(which nvim)"
export VISUAL="$(which nvim)"
alias vi="$(which nvim)"
