---
- name: install docker (all)
  become: yes
  package:
    name:
      - docker
    state: latest
  when: (ansible_facts['distribution'] != "Fedora")

- name: install docker
  become: yes
  package:
    name:
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - docker-scan-plugin
    state: latest
  when: (ansible_facts['distribution'] == "Fedora")

- name: install docker-compose
  become: yes
  get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

