---
- name: get Go version (if present)
  command: go version
  register: goversion
  when:
    - "'/usr/local/go/bin/go' is file"

- name: delete previous Go installations before updating
  become: yes
  file:
    state: absent
    path: /usr/local/go
  when:
    - go_version is undefined or goversion != "go version go{{ go_version }} linux/{{ arch }}"
      
- name: install Go 
  become: yes
  unarchive:
    src: https://golang.org/dl/go{{ go_version }}.linux-{{ arch }}.tar.gz
    dest: /usr/local
    remote_src: yes
  when:
    - go_version is undefined or goversion != "go version go{{ go_version }} linux/{{ arch }}"

- name: symlink go
  become: yes
  file:
    src: /usr/local/go/bin/go
    dest: /usr/local/bin/go
    state: link

- name: symlink gofmt
  become: yes
  file:
    src: /usr/local/go/bin/gofmt
    dest: /usr/local/bin/gofmt
    state: link
