---
- name: install neovim
  become: yes
  get_url:
      url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
      dest: /usr/local/bin/nvim
      mode: 0755

- name: configure neovim
  copy:
      src: files/nvim
      dest: ~/.config

- name: install neovim plugins
  command: /usr/local/bin/nvim -c 'PlugInstall' -c ':qa!'
